spring:
  application:
    name: TrafficAI
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
springdoc:
  swagger-ui:
    path: "/traffic/backend/"
  api-docs:
    path: "/traffic/backend/v3/api-docs"
server:
  port: 8081
traffic-ai:
  frame-extraction:
    interval-seconds: 5
custom-vision:
  prediction:
    key: ${CV_PREDICTION_KEY}
    endpoint: ${CV_PREDICTION_ENDPOINT}
    project-id: ${CV_PREDICTION_PROJECT_ID}
    published-name: ${CV_PREDICTION_PUBLISHED_NAME}
    prediction-threshold: 0.7
